/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Mobilehouse_inside.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall001.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall002.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall003.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle_Argos003.geometry}
        material={materials['aluminium used.001']}
        position={[0.487, 0.056, -0.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle_Argos004.geometry}
        material={materials['aluminium used.002']}
        position={[0.87, 0.056, -1.868]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall004.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall005.geometry}
        material={materials.WoodenFloor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall006.geometry}
        material={materials.Tiles}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.topback.geometry}
        material={materials['Artificial Marble 1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.top.geometry}
        material={materials['Artificial Marble 1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.simple_tap01001.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate_Stack001.geometry}
        material={materials.Cup}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['cooking mat']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hood.geometry}
        material={materials['brushed metal hood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle013.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle012.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle011.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle010.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle009.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle008.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle007.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle005.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle004.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle003.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle002.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handle001.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cup-Large-White003'].geometry}
        material={materials.Cup}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['brushed metal hood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cooking_stove.geometry}
        material={materials['brushed metal']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_wall_40004.geometry}
        material={materials['cabinets gray']}
        position={[-1.698, 0.702, 1.986]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.518, 1, 1.433]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_wall_40003.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_wall_40002.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_wall_40001.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_60x82003.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_60x82002.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_60x82001.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82016.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82015.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82014.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82013.geometry}
        material={materials['front pannels']}
        position={[-1.241, 1.062, 1.973]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.518, 1, 1.433]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82012.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82011.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82010.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82009.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82008.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82006.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82005.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82004.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82003.geometry}
        material={materials['front pannels']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bootom_stand.geometry}
        material={materials['cabinets gray']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_decor_wall.geometry}
        material={materials['back wall']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_wall_40005.geometry}
        material={materials['cabinets gray.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cabinet_ground_40x82017.geometry}
        material={materials['cabinets gray.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.houseWall007.geometry}
        material={materials['Tiles.001']}
      />
      <mesh castShadow receiveShadow geometry={nodes.tap.geometry} material={materials.Chrome} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sink_hole.geometry}
        material={materials['Anodized.001']}
      />
      <mesh castShadow receiveShadow geometry={nodes.sink.geometry} material={materials.Ceramic} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_upper_door.geometry}
        material={materials['White - Cristallo']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handles.geometry}
        material={materials['Anodized.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials.Chrome}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handles001.geometry}
        material={materials['Anodized.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_1.geometry}
        material={materials['WinDoor_Glass.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_2.geometry}
        material={materials['Edit_WinDoors.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_PI002.geometry}
        material={materials['Wood Base 01']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame.geometry}
        material={materials['Wood Base 01']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_PI002001.geometry}
        material={materials['Wood Base 01']}
        position={[0.484, 0.173, -1.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame001.geometry}
        material={materials['Wood Base 01']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle_Argos001.geometry}
        material={materials['aluminium used']}
        position={[0.479, 0.056, -1.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_PI002002.geometry}
        material={materials['Wood Base 01']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame002.geometry}
        material={materials['Wood Base 01']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.table}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['grid plastic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018_1.geometry}
        material={materials['darkish grey plastic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018_2.geometry}
        material={materials.screen}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_1.geometry}
        material={materials.sink}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_2.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_3.geometry}
        material={materials['sink side hole']}
      />
      <mesh castShadow receiveShadow geometry={nodes.Plane_1.geometry} material={materials.grate} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials['brushed metal']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_3.geometry}
        material={materials.plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001_1.geometry}
        material={materials.Anodized}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001_2.geometry}
        material={materials['tap hole']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.prop_chair_karlstad.geometry}
        material={materials['Chair fabric']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.prop_chair_karlstad_1.geometry}
        material={materials['chair wood']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials['metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010_1.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010_2.geometry}
        material={materials['plastic.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back002.geometry}
        material={materials['Dark glossy']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.decorative_board002.geometry}
        material={materials['Dark glossy']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handles002.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_drawersdoor.geometry}
        material={materials['Wood.001']}
      />
      <mesh castShadow receiveShadow geometry={nodes.legs002.geometry} material={materials.Metal} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_door001.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shelves.geometry}
        material={materials['Dark glossy']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials['wood frame']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_1.geometry}
        material={materials['Dark glossy']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={materials.Metallight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032_1.geometry}
        material={materials['LED-Lighitngs']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Metallight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015_1.geometry}
        material={materials['LED-Lighitngs']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Toilet-01_1'].geometry}
        material={materials['white ceramic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Toilet-01_2'].geometry}
        material={materials['chrome metal']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Toilet-01_3'].geometry}
        material={materials['White plastic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube000.geometry}
        material={materials['porcelain white']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['porcelain white']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sink_1.geometry}
        material={materials['porcelain white']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sink_2.geometry}
        material={materials['chrome.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={materials['Heat_Source Metal']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_1.geometry}
        material={materials['Heat_Source Tape']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_2.geometry}
        material={materials['Heat_Plastic Overlay']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_3.geometry}
        material={materials.Heat_Plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_4.geometry}
        material={materials['Heat_Black Plastic']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_5.geometry}
        material={materials['Heat_Rubber Hose']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_6.geometry}
        material={materials['Heat_Stainles Tube']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Scuffed Aluminum']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_left.geometry}
        material={materials['Scuffed Aluminum']}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door_left_glass.geometry}
          material={materials['Architectural Glass']}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_right.geometry}
        material={materials['Scuffed Aluminum']}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door_right_glass.geometry}
          material={materials['Architectural Glass']}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DOWN.geometry}
        material={materials['Material.002']}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body.geometry}
          material={materials['Scuffed Aluminum']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall.geometry}
          material={materials['Scuffed Aluminum']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall_glass.geometry}
          material={materials['Architectural Glass']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall_right.geometry}
          material={materials['Scuffed Aluminum']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall_right_glass.geometry}
          material={materials['Architectural Glass']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={materials['Procedural rough Concrete']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_2.geometry}
          material={materials['Die-cast aluminum']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_3.geometry}
          material={materials['Scuffed Aluminum']}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grid.geometry}
        material={materials['Scuffed Aluminum']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials['White - Cristallo']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073_1.geometry}
        material={materials.Chocofur_Wood_Solid_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002_1.geometry}
        material={materials['Anodized.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002_2.geometry}
        material={materials.mesh}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials['White - Cristallo']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071_1.geometry}
        material={materials.Chocofur_Wood_Solid_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials.mirror}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030_1.geometry}
        material={materials['White - Cristallo']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Anodized.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_1.geometry}
        material={materials.mesh}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chocofur_Free_Beds_01002.geometry}
        material={materials['Unmade bed']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chocofur_Free_Beds_01002_1.geometry}
        material={materials['Unmade bed.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chocofur_Free_Beds_01002_2.geometry}
        material={materials['Unmade bed.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chocofur_Free_Beds_01002_3.geometry}
        material={materials['Unmade bed.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chocofur_Free_Beds_01002_4.geometry}
        material={materials['Unmade bed.004']}
      />
    </group>
  )
}

useGLTF.preload('/Mobilehouse_inside.glb')
